### ISSUE TITLE
Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by quantuminformation** [thecodejack/svelte-switch#1]
Hello thanks for converting this.

I am trying to use this on my side but get the following:

![image](https://user-images.githubusercontent.com/216566/91253850-1fd33200-e761-11ea-9198-dde8d77c547e.png)

**Comment by thecodejack** [comment]
Missed this one. Will push a fix soon

**Comment by thecodejack** [comment]
This is fixed in latest.

**Comment by quantuminformation** [comment]
thx

**Comment by quantuminformation** [comment]
you should sign up and add site to a list of being used by)

https://mentorcv.com/

**Comment by quantuminformation** [comment]
oh sorry, im using svelte-toggle
