### ISSUE TITLE
Cannot change checkedIcon / uncheckedIcon

### ISSUE THREAD

**Issue by gudwns0102** [thecodejack/svelte-switch#21]
Hi! Thank you for maintain this repository. Very useful. 

I found that checkedIcon and uncheckedIcon is not working.

I guess in src/components/Switch.svelte, CIcon and UIcon need to be changed like below. 

```
  let CIcon = checkedIcon;
  let UIcon = unCheckedIcon;
```

I tested it locally and it works as expected. Could you check this out? Thank you in advance :)

**Comment by thecodejack** [comment]
Fixing

**Comment by thecodejack** [comment]
this is fixed in v0.0.4
